Repository andrijzyn/The-Undefinders, pull requests merged in 2025-03, with the labels that each got.

#35 Optimizations for HearthBar & Units
  app/game_scene_path.tscn
  entities/Units/USA/Infantry/Soldier/soldier.gd
  shared/AbstractClasses/MovableUnit.gd
  shared/AbstractClasses/UnitConfig.gd
  shared/HUD/healthBar/HealthBar.gd
  shared/HandlerClasses/HoverHandler.gd
  shared/HandlerClasses/MouseChanger.gd
  shared/HandlerClasses/OrderHandler.gd
  shared/HandlerClasses/SelectionHandler.gd
  shared/HandlerClasses/UI.gd
  shared/UtilityClasses/Constants.gd
Labels: enhancement

#36 [Initial importance, InputMap is involved] Edge scrolling fix & cleanup
  app/MainCamera.gd
  project.godot
  shared/HandlerClasses/OrderHandler.gd
  shared/HandlerClasses/UI.gd
Labels: bug

#37 Fixes
  addons/maaacks_game_template/base/scenes/menus/main_menu/main_menu.tscn
  addons/maaacks_game_template/base/translations/menus_translations.en.translation
  addons/maaacks_game_template/base/translations/menus_translations.fr.translation
  app/main_scene.tscn
  shared/AbstractClasses/MovableUnit.gd
Labels: Fix

#41 Composition rework
  app/MainCamera.gd
  app/main_scene.tscn
  entities/Buildings/GLA/garage/garage_imp.tscn
  entities/Units/USA/Infantry/Soldier/soldier.gd
  entities/Units/USA/Infantry/Soldier/soldier.tscn
  features/HUD/UI/UI.gd
  features/HUD/UI/UI.gd.uid
  features/HUD/UI/action_button.tscn
  features/HUD/UI/group_icon.tscn
  features/HUD/UI/rts_ui.tscn
  features/HUD/UI/ui_button_down.tscn
  features/HUD/UI/ui_button_up.tscn
  features/HUD/UI/unit_icon.tscn
  features/HUD/healthBar/HealthBar.gd
  features/HUD/healthBar/HealthBar.gd.uid
  features/HUD/healthBar/health_bar.tscn
  features/HUD/queueProduce/queue_producer.gd
  features/HUD/queueProduce/queue_producer.gd.uid
  features/HUD/queueProduce/queue_producer.tscn
  features/HUD/queueProduce/queue_product.gd
  features/HUD/queueProduce/queue_product.gd.uid
  features/HUD/queueProduce/queue_product.tscn
  shared/AbstractClasses/Entity.gd
  shared/AbstractClasses/Entity.gd.uid
  shared/AbstractClasses/MovableUnit.gd
  shared/AbstractClasses/UnitConfig.gd
  shared/AbstractClasses/UnitConfig.gd.uid
  shared/HandlerClasses/MouseChangeHandler.gd
  shared/HandlerClasses/MouseChangeHandler.gd.uid
  shared/HandlerClasses/OrderHandler.gd
  shared/HandlerClasses/OrderHandler.gd.uid
  shared/HandlerClasses/PathHandler.gd
  shared/HandlerClasses/PathHandler.gd.uid
  shared/HandlerClasses/RaycastHandler.gd
  shared/shaders/ghost_shader.gdshader
  shared/shaders/ghost_shader.gdshader.uid
Labels: enhancement, documentation, Critical
